branches:
  only:
    - master
    - devel

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

platform: x86

environment:
  aws_access_key_id:
    secure: veTfhOrd4wUpG7NlRsvS3tufuaFfST8i7SZa2HVH6Vc=
  aws_secret_access_key:
    secure: nCQcN/Mzce0erwcNOU3yAuWgF6ZuTvPBEqTF3XFp1poGcDbSIg+s67eVxsxWCXQj
  GCP_CREDS:
    secure: 96fJ3r2i2GohbXHwnSs5N4EplQ7q8YmLpPWM0AC+f4s=
  CODECOV_TOKEN:
    secure: XN4jRtmGE5Bqg8pPZkwNs7kn3UEI73Rkldqc0MGsQISZBm5TNJZOPofDMc1QnUsf
  AZURE_STORAGE_CONTAINER_NAME: appveyor-tests
  AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
  OSS_ENDPOINT: localhost:50004
  OSS_ACCESS_KEY_ID: AccessKeyID
  OSS_ACCESS_KEY_SECRET: AccessKeySecret

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"
      RUBY: C:\Ruby25\bin

# Disabled as unnecessary
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.x" # currently 2.7.9
#      PYTHON_ARCH: "64"

install:
  - SET PATH=%RUBY%;%PATH%
  - git clone -q https://github.com/nanaya-tachibana/oss-emulator.git
  - gem install thor builder
  - ps: cd oss-emulator
  - ps: $OSSProcess = Start-Process -FilePath ruby -ArgumentList "bin\emulator -r store -p 50004" -PassThru -NoNewWindow
  - ps: cd ..
  - npm install -g azurite
  - ps: $AzuriteProcess = Start-Process azurite-blob -PassThru
  - cinst wget
  - cinst awscli
  - cinst gcloudsdk
  - refreshenv
  - cinst gsutil
  - cinst openssl.light --version 1.1.1
  - python -m pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - python setup.py install

build: false

before_test:
  - aws configure set aws_access_key_id "%aws_access_key_id%"
  - aws configure set aws_secret_access_key "%aws_secret_access_key%"
  - aws configure set region us-east-2
  - openssl enc -d -aes-256-cbc -md md5 -k "%GCP_CREDS%" -in scripts\ci\gcp-creds.json.enc -out scripts\ci\gcp-creds.json & exit 0
  - pip install -r tests/requirements.txt

test_script:
  - python -mtests

after_test:
  - if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" pip install codecov
  - if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" codecov

before_deploy:
  - if "%APPVEYOR_REPO_TAG%"=="true" python -m dvc pull
  - if "%APPVEYOR_REPO_TAG%"=="true" .\scripts\build_windows.cmd

on_finish:
  - ps: Stop-Process $AzuriteProcess
  - ps: Stop-Process $OSSProcess

artifacts:
  - path: dvc*.exe
    name: DVC Installer

deploy:
  provider: GitHub
  auth_token:
    secure: 25c1pNoXWbtTwUkKLcThwcl2A2xG8oXHsPuD73HVbQ7SRy9X6HzkCc2sXzhpfRtF
  on:
    APPVEYOR_REPO_TAG: true
