default_language_version:
  python: python3

ci:
  skip: [mypy, dvc-pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
        exclude: "tests/func/utils/test_strict_yaml.py"
        args: ['--assume-in-merge']
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      files: ^dvc/
      language: system
      types: [python]
      require_serial: true
  - hooks:
      - args:
          - git-hook
          - pre-commit
        entry: dvc
        id: dvc-pre-commit
        language: system
        name: DVC pre-commit
        stages:
          - commit
        verbose: true
        require_serial: true
      - args:
          - git-hook
          - pre-push
        entry: dvc
        id: dvc-pre-push
        language: system
        name: DVC pre-push
        stages:
          - push
        require_serial: true
      - always_run: true
        args:
          - git-hook
          - post-checkout
        entry: dvc
        id: dvc-post-checkout
        language: system
        minimum_pre_commit_version: 2.2.0
        name: DVC post-checkout
        stages:
          - post-checkout
        require_serial: true
    repo: local
