default_language_version:
  python: python3

ci:
  skip: [mypy, pylint, dvc-pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
        exclude: "tests/func/utils/test_strict_yaml.py"
        args: ['--assume-in-merge']
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
        exclude: "dvc/_debug.py"
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args: ["-i", "2"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.278'
    hooks:
      - id: ruff
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-string-format
          - flake8-typing-imports
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml", "--quiet", "--format=custom"]
      files: ^dvc/
      additional_dependencies: [".[toml]"]
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      files: ^dvc/
      language: system
      types: [python]
      require_serial: true
    - id: pylint
      name: pylint
      entry: pylint
      files: ^dvc/
      language: system
      types: [python]
      require_serial: true
  - hooks:
      - args:
          - git-hook
          - pre-commit
        entry: dvc
        id: dvc-pre-commit
        language: system
        name: DVC pre-commit
        stages:
          - commit
        verbose: true
        require_serial: true
      - args:
          - git-hook
          - pre-push
        entry: dvc
        id: dvc-pre-push
        language: system
        name: DVC pre-push
        stages:
          - push
        require_serial: true
      - always_run: true
        args:
          - git-hook
          - post-checkout
        entry: dvc
        id: dvc-post-checkout
        language: system
        minimum_pre_commit_version: 2.2.0
        name: DVC post-checkout
        stages:
          - post-checkout
        require_serial: true
    repo: local
