ci:
  skip: [mypy, pylint, dvc-pre-commit]

repos:
  - hooks:
      - id: black
        language_version: python3
    repo: https://github.com/ambv/black
    rev: 22.3.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
  - hooks:
      - id: codespell
        args: 
          - --ignore-words-list
          - ba,datas,fo,uptodate,cachable
    repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
  - hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-string-format
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      files: ^dvc/
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
  - hooks:
      - args:
          - -i
          - "2"
        id: beautysh
        language_version: python3
    repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
  - hooks:
      - args:
          - git-hook
          - pre-commit
        entry: dvc
        id: dvc-pre-commit
        language: system
        name: DVC pre-commit
        stages:
          - commit
        verbose: true
        require_serial: true
      - args:
          - git-hook
          - pre-push
        entry: dvc
        id: dvc-pre-push
        language: system
        name: DVC pre-push
        stages:
          - push
        require_serial: true
      - always_run: true
        args:
          - git-hook
          - post-checkout
        entry: dvc
        id: dvc-post-checkout
        language: system
        minimum_pre_commit_version: 2.2.0
        name: DVC post-checkout
        stages:
          - post-checkout
        require_serial: true
    repo: local
