language: python
cache:
  - pip
  - directories:
    - /opt/python
    - $HOME/.pyenv
sudo: true
dist: xenial
python: "3.7"
env:
  global:
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
# Travis doesn't support testing python on Mac yet, so we need
# to workaround it by installing it directly with brew.
#
# Note that we specify language as ruby-2.4.0 to help us satisfy
# fpm dependencies, as travis runs el capitan with an old ruby
# version, that causes fpm to crash.
matrix:
  include:
  - name: "2.7"
    env:
    - PYTHON_VER=2.7.13
  - name: "3.5"
    env:
    - PYTHON_VER=3.5.3
  - name: "3.6"
    env:
    - PYTHON_VER=3.6.2
  - name: "3.7"
    env:
    # NOTE: using default python
    - PYTHON_VER=
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=2.7.10
    - CPPFLAGS="-I/usr/local/opt/openssl/include $CPPFLAGS"
    - LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=3.7.3
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode7.3
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=3.5.0
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode10.1
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=2.7.10
    - CPPFLAGS="-I/usr/local/opt/openssl/include $CPPFLAGS"
    - LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
  - if: type = cron OR tag is present
    os: osx
    osx_image: xcode10.1
    language: ruby
    rvm: 2.4.0
    env:
    - PYTHON_VER=3.5.0
    - PYTHON_CONFIGURE_OPTS="--enable-framework"
before_install:
  - bash ./scripts/ci/before_install.sh
  - source env.sh
  - python --version
install:
  - bash ./scripts/ci/install.sh
script:
  - bash ./scripts/ci/script.sh
before_deploy:
  - bash ./scripts/ci/before_deploy.sh
  - pip install twine
deploy:
  - provider: releases
    condition: "[[ $(./scripts/ci/deploy_condition.sh) == 'true' ]]"
    api_key:
      secure: nyo17gF4Xl6DFL/KVkMewC805Cv+eK99L7SiYCU+WUAYDIzzFL3YJm7fm8bznPeor7DmpO7uSLSveMnJETBtdurW6JWhCTUss4yD66yFzpk6Z5cvHf/1UA5pdMHkkMM54fRaTRt6L2Yal7RPwGEQTBECLXW1Xmf78Y6+0l8lTvXQ9jXOQSRO/63VDKI5Zww2+XytVicUFlr0hLMGKUuaCjjXcQlAPzBgQz3/5Iz6EtzeTf2o+gTPjocbRbSFPikfiBXUn8XlJ8jBj7i114XJRJffw59KxYGDzxp+enfLBULGNoW0Np2hZqkKkPUIdB08C8XVbRXlFYX8cEYBczjqhv8A05p5F5CnltnqQ0KazcoUP2awPVqn68dWNRF+kqrnMBus8euYKIZ4dy/6bVEKJRa84ESJXZVDcwXTAXRqyovSxOlXqg9ZgAImMKBfKn/fpDX2xIvQPaXcnJxKbmcePfdbC1d0HYJ5jkbNaxKE/T15VvhzIho7mJ2WAv1r8QouQUuzqtpzIGbRn/KXHRUzCtyP0k4+eMKMLFOPzg848WsDarP3v8VYiSy4nFY7ZP7DRd3KttvW5bgVbSeO4jPmTgS6TnnpRwual9BJXSG7bjbfpIMii3bNZ7jWL4zpKT9Jfm8w9RGKLcX9HqkZ3+y60+LtYdhEfBvqsIlWQoIJBXg=
    file_glob: true
    file:
      - dvc*.rpm
      - dvc*.deb
      - dvc*.pkg
    skip_cleanup: true
    on:
      tags: true
      repo: iterative/dvc
  - provider: pypi
    user:
      secure: "IOzNfgPoG3ICg3+s4AuZCCnawgd/KqMzeiAB9R0B9Xb6ProPQJp9O3GBZrtg5OJMHdWQQtwULeOh/LWk4sFdXMcX1iNEgm5Tb7DwO7TDtltW14jUgN9AqfY2twj4UIsW/ON8w0P8v36ZoQq1kO6Pfgjijdm3w+9h6rpps8rJ6jXYpVZVO+SSzzijWddanMkEz4GgctZ2r7U5MWlmm1UogF60kEZIZCQykz0yJnhTpP9nMFDKw6Maki/mcfVwTQ/v3RqjzttHei/aaEMGQXYr3TOX8NPYJXerBpjShDZqcgcCfqPzhi7uCwVYaPvRsMMYH5jgtMz/SO3J6ToeGKT0f1F1ihRyCdusg325TMK7Vv8yHJzL4ngeUbb/oqxWtxhLY7f77Lkx6hBwe6ROpTqiQHIfZad5qyIHihKcDcIHo4FwLHVzxR4y+Ds2js5dXwBkUBaEAx0Dmc6ZdgXqxd815GDwv+VVpzXJhtO6qXmKE36F/Oe6eCNG3dk5MdOK4C2DrM9M8MXllqeQtX6JrM2stWlBalAc9Jn4b0xxAoghX3x3G3hNsLc9Uist1VinY2+IcPozusqj66c+Vbi5YngWSbICOjlIcq2GaOlBi3xioGts396442ztf1eLjMVuvykCI3b4Yz/vJYZOZjUvG/6nLfaFQTJLSXkTvI4do3foeY4="
    password:
      secure: "ts/3FSPL+w4euXryip9wCJWUqUwuJ2CqHi0nEpYVM10KL0cp9aMkQXN/7C8ih+j/JZ25kaO+tis1nx0JERVnKrg/1F/fJhxHTpakCP4OSIlhKRXDt7yUUHcKKt5QdM2XCKhApptP6RTpWL1vlc36CMrhdvTcMYp7hlDOiWjdhhim24FGQzabL42Ko59ttyyCROqgcnjHqj+WlhJl7iYO+lv2PLOtslpkIYY5EMjgBLuGyOvxTqZsAXtworsASdB2CrsTE6iMRcrM1afgkyBlUqDezoiv9TwfZrZ85oRoAxPB7su4QWK7lEP0wGQV/SDz/RL7c+cNfRaauxUKVcC8I2LfaEpudv8vi205+v/08wzPbS4xSOnf89irUJnyGxUy+bYLoXPPVPMyzcQRAUnrQl+ENCmN62HU+/2pkIyiUJvt0wYYP0vp+3pIbXbYQGmAIMq7nZJd7K3rikfnQIGKI03xZsFe3PEdjzhDI9Ej/tRUbJx4pgg084QuYYca6MSYn/zJ5pqIG4A7ngCSxoxoWZT0duo8PrUWQeT17L73Q86HeEv3OzZhWfEF2fNDN3Qbsu4CllSZnbE7DXgAuysTwTYHS/na6lp7wejOqdRUXrHbidVla9Mwxyc9JdWNWzUDxALvNxAdNbV6l85mO8izy8wjQF6M1O7idqTfjQeR4pc="
    skip_existing: true
    file_glob: true
    file:
      - dist/dvc*.whl
      - dist/dvc*.tar.gz
    skip_cleanup: true
    on:
      tags: true
      repo: iterative/dvc
