client_config_backend: settings
client_config:
  client_id: 470227652556-1n09ue25mtb7gp66i4lvks3jompjisen.apps.googleusercontent.com
  client_secret: 0ipFt0Dn4V_Tge6kw7aiu0GR

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.appdata